spring:
  datasource:
    url: jdbc:mysql://172.16.10.23:3306/information_schema?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&allowMultiQueries=true
    username: root
    password: biosan#17
